version: '2'
services:
  openai-linebot:
    image: openai-linebot:latest
    container_name: openai-linebot
    ports:
      - 80:80
    volumes:
      - ./data:/bot/data

  grafana:
    image: openai-linebot-grafana:latest
    container_name: grafana
    ports:
      - 8080:8080
    volumes:
      - ./data:/opt/grafana
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource, grafana-image-renderer
    user: "472"

  flowise:
    image: flowiseai/flowise
    environment:
        - PORT=3000
        - DATABASE_PATH=/root/.flowise
        - APIKEY_PATH=/root/.flowise
        - LOG_PATH=/root/.flowise/logs
    ports:
        - '3000:3000'
    volumes:
        - ./data/flowise:/root/.flowise
        - ./data:/bot/data
    command: /bin/sh -c "sleep 3; flowise start"

# volumes:
#   shared-volume:
#   flowise-volume: