version: '2'
services:
  openai-linebot:
    image: openai-linebot:latest
    pull_policy : never
    container_name: openai-linebot
    ports:
      - 80:80
    volumes:
      - shared-volume:/bot/data

  grafana:
    image: openai-linebot-grafana:latest
    pull_policy : never
    container_name: grafana
    ports:
      - 8080:8080
    volumes:
      - shared-volume:/opt/grafana
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource, grafana-image-renderer
    user: "472"

  flowise:
    image: flowiseai/flowise
    environment:
        - PORT=3000
        - DATABASE_PATH=/root/.flowise
        - APIKEY_PATH=/root/.flowise
        - LOG_PATH=/root/.flowise/logs
    ports:
        - '3000:3000'
    volumes:
        - flowise-volume:/root/.flowise
        - shared-volume:/bot/data
    command: /bin/sh -c "sleep 3; flowise start"

volumes:
  shared-volume:
  flowise-volume: