version: '2'
services:
  openai-linebot:
    image: openai-linebot:latest
    container_name: openai-linebot
    ports:
      - 80:80
    volumes:
      - ./data:/bot/data
      - ./resources:/bot/resources
    environment:
      - SYSTEM_PORT=80

  grafana:
    image: openai-linebot-grafana:latest
    container_name: grafana
    ports:
      - 8080:8080
    volumes:
      - ./data:/opt/grafana
    environment:
      # - GF_SECURITY_ADMIN_USER=username
      # - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_RENDERING_SERVER_URL=http://grafana-render:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:8080/
      - GF_LOG_FILTERS=rendering:debug
    user: "472"

  grafana-render:
    image: grafana/grafana-image-renderer:latest
    # ports:
    #   - 8081:8081

  flowise:
    image: flowiseai/flowise
    environment:
        - FLOWISE_USERNAME=username
        - FLOWISE_PASSWORD=password
        - PORT=3000
        - DATABASE_PATH=/root/.flowise
        - APIKEY_PATH=/root/.flowise
        - LOG_PATH=/root/.flowise/logs
    ports:
        - '3000:3000'
    volumes:
        - ./data/flowise:/root/.flowise
        - ./data:/bot/data
    command: /bin/sh -c "sleep 3; flowise start"

  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.10.2
    volumes:
      - ./default/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data:/bot/data
    environment:
      - DEVICE_NAME=device_name
      - ES_HOST=[hostname]
      - ES_USER=username
      - ES_PASS=password
    command: bash -c "filebeat -e -strict.perms=false"

  postgres:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
