apiVersion: v1
kind: PersistentVolume
metadata:
  name: openai-linebot-pv
  labels:
    type: local
spec:
  storageClassName: openai-linebot-pv
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/openai-linebot"
    type: "DirectoryOrCreate"