apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-openai-linebot
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: openai-linebot-pv